# Etapa 1 — Build
FROM node:22-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG NEXT_PUBLIC_API_URL
ARG AUTH_KEYCLOAK_ID
ARG AUTH_KEYCLOAK_SECRET
ARG AUTH_KEYCLOAK_ISSUER
ARG AUTH_KEYCLOAK_ADMIN
ARG NEXT_PUBLIC_TARGET_URL
ARG PUBLIC_KEY
ARG NEXT_HOSTNAME

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV AUTH_KEYCLOAK_ID=$AUTH_KEYCLOAK_ID
ENV AUTH_SECRET=$AUTH_SECRET
ENV AUTH_KEYCLOAK_SECRET=$AUTH_KEYCLOAK_SECRET
ENV AUTH_KEYCLOAK_ISSUER=$AUTH_KEYCLOAK_ISSUER
ENV AUTH_KEYCLOAK_ADMIN=$AUTH_KEYCLOAK_ADMIN
ENV NEXT_PUBLIC_TARGET_URL=$NEXT_PUBLIC_TARGET_URL
ENV PUBLIC_KEY=$PUBLIC_KEY
ENV NEXT_HOSTNAME=$NEXT_HOSTNAME

RUN npm run build

# Etapa 2 — Runner (imagem final leve)
FROM node:22-slim AS runner

WORKDIR /app

ENV NODE_ENV=production

# Copia apenas os arquivos necessários do standalone
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["node", "server.js"]